version: '2.3'
services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20
  workspace:
    # env_file:
    #   - .env
    image: my-ros-devcontainer-vscode:humble-desktop
    #build: 
    #  context: .
    #  dockerfile: Dockerfile
    #  tag: my-ros-devcontainer-vscode:humble-desktop
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "3001:3000"
    - "3002:8888"
    volumes:
    - workspace:/workspace
    environment:
    - DISPLAY=:0
    volumes_from:
    - xserver
    depends_on:
    - xserver
volumes:
  workspace:
